import type { Vehicle, ContactMessage, Scheduling } from './types'

export const mockVehicles: Vehicle[] = [
  {
    id: '1',
    brand: 'Porsche',
    model: '911 Carrera S',
    year: 2024,
    price: 1250000,
    mileage: 5200,
    color: 'Cinza Ártico Metálico',
    transmission: 'automatic',
    fuel: 'gasoline',
    doors: 2,
    engine: '3.0 Boxer 6 cilindros Twin-Turbo',
    power: '450 cv',
    features: [
      'Teto solar panorâmico',
      'Interior em couro premium',
      'Sistema de som Bose Surround',
      'Faróis LED Matrix',
      'Suspensão ativa PASM',
      'Freios cerâmicos PCCB',
      'Sport Chrono Package',
      'Bancos esportivos adaptativos',
    ],
    images: [
      '/vehicles/porsche-911-turbo-s.jpg',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200',
      'https://images.unsplash.com/photo-1580274455191-1c62238fa333?w=1200',
    ],
    description: 'O Porsche 911 Carrera S é o ícone automotivo por excelência. Com seu motor boxer de 450 cv e design atemporal, oferece uma experiência de condução incomparável.',
    status: 'available',
    featured: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    brand: 'Mercedes-Benz',
    model: 'AMG GT 63',
    year: 2023,
    price: 980000,
    mileage: 12000,
    color: 'Preto Obsidiana',
    transmission: 'automatic',
    fuel: 'gasoline',
    doors: 4,
    engine: '4.0 V8 Biturbo',
    power: '639 cv',
    features: [
      'AMG Performance 4MATIC+',
      'Interior AMG em couro Nappa',
      'Sistema Burmester High-End 3D',
      'Tela MBUX de 12.3"',
      'Head-up display',
      'Câmeras 360°',
      'Suspensão AMG RIDE CONTROL+',
    ],
    images: [
      '/vehicles/mercedes-amg-gt.jpg',
      'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=1200',
    ],
    description: 'O Mercedes-AMG GT 63 combina performance brutal com luxo refinado. Um super sedan que desafia as leis da física.',
    status: 'available',
    featured: true,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: '3',
    brand: 'BMW',
    model: 'M4 Competition',
    year: 2024,
    price: 720000,
    mileage: 3500,
    color: 'Azul São Paulo',
    transmission: 'automatic',
    fuel: 'gasoline',
    doors: 2,
    engine: '3.0 6 cilindros em linha Twin-Turbo',
    power: '510 cv',
    features: [
      'M xDrive',
      'Bancos M Sport',
      'Harman Kardon Surround',
      'BMW Live Cockpit Professional',
      'Teto de carbono',
      'Diferencial M ativo',
      'Freios M Compound',
    ],
    images: [
      '/vehicles/bmw-m4-competition.jpg',
      'https://images.unsplash.com/photo-1617814076668-8dbf3f3c6e03?w=1200',
    ],
    description: 'O BMW M4 Competition é a expressão máxima da esportividade BMW. Poder bruto aliado à precisão alemã.',
    status: 'available',
    featured: true,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-05'),
  },
  {
    id: '4',
    brand: 'Audi',
    model: 'RS e-tron GT',
    year: 2024,
    price: 1150000,
    mileage: 8000,
    color: 'Branco Ibis',
    transmission: 'automatic',
    fuel: 'electric',
    doors: 4,
    engine: 'Dois motores elétricos',
    power: '646 cv',
    features: [
      'Quattro elétrico',
      'Autonomia de 472 km',
      'Carregamento ultrarrápido 270 kW',
      'Bang & Olufsen 3D',
      'Matrix LED',
      'Audi Virtual Cockpit Plus',
      'Suspensão pneumática adaptativa',
    ],
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200',
      'https://images.unsplash.com/photo-1614200187524-dc4b892acf16?w=1200',
    ],
    description: 'O Audi RS e-tron GT representa o futuro da performance elétrica. Aceleração brutal com zero emissões.',
    status: 'reserved',
    featured: true,
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-12'),
  },
  {
    id: '5',
    brand: 'Land Rover',
    model: 'Range Rover Autobiography',
    year: 2023,
    price: 890000,
    mileage: 18000,
    color: 'Verde Santorini',
    transmission: 'automatic',
    fuel: 'diesel',
    doors: 5,
    engine: '3.0 Diesel 6 cilindros',
    power: '350 cv',
    features: [
      'Interior Executive Class',
      'Bancos massageadores',
      'Meridian Signature Sound',
      'Pivi Pro 13.1"',
      'Suspensão a ar adaptativa',
      'Terrain Response 2',
      'Teto panorâmico duplo',
    ],
    images: [
      '/vehicles/range-rover-sport.jpg',
      'https://images.unsplash.com/photo-1519245659620-e859806a8d3b?w=1200',
    ],
    description: 'O Range Rover Autobiography define o padrão de luxo para SUVs. Elegância suprema em qualquer terreno.',
    status: 'available',
    featured: false,
    createdAt: new Date('2023-12-20'),
    updatedAt: new Date('2023-12-20'),
  },
  {
    id: '6',
    brand: 'Ferrari',
    model: 'Roma',
    year: 2023,
    price: 2800000,
    mileage: 4500,
    color: 'Rosso Corsa',
    transmission: 'automatic',
    fuel: 'gasoline',
    doors: 2,
    engine: '3.9 V8 Biturbo',
    power: '620 cv',
    features: [
      'Manettino no volante',
      'Sistema de som JBL Premium',
      'Interior em couro e Alcantara',
      'Display 16" curvo',
      'SCM-E magnetoreológico',
      'Câmeras 360°',
      'Ferrari Dynamic Enhancer',
    ],
    images: [
      'https://images.unsplash.com/photo-1592198084033-aade902d1aae?w=1200',
      'https://images.unsplash.com/photo-1583121274602-3e2820c69888?w=1200',
    ],
    description: 'A Ferrari Roma é a definição de elegância italiana. Um GT com alma de supercarro.',
    status: 'available',
    featured: true,
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
  },
  {
    id: '7',
    brand: 'Lamborghini',
    model: 'Huracán EVO',
    year: 2023,
    price: 3200000,
    mileage: 6200,
    color: 'Verde Mantis',
    transmission: 'automatic',
    fuel: 'gasoline',
    doors: 2,
    engine: '5.2 V10 naturalmente aspirado',
    power: '640 cv',
    features: [
      'LDVI (Lamborghini Dinamica Veicolo Integrata)',
      'Suspensão MagneRide',
      'Sistema de escapamento Lamborghini',
      'Interior Alcantara premium',
      'Telemetria em tempo real',
      'Aerodinâmica ativa',
    ],
    images: [
      'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200',
      'https://images.unsplash.com/photo-1621135802920-133df287f89c?w=1200',
    ],
    description: 'O Lamborghini Huracán EVO é pura adrenalina. O lendário V10 em sua forma mais evoluída.',
    status: 'sold',
    featured: false,
    createdAt: new Date('2023-11-15'),
    updatedAt: new Date('2024-01-10'),
  },
  {
    id: '8',
    brand: 'Volvo',
    model: 'XC90 Recharge',
    year: 2024,
    price: 580000,
    mileage: 2000,
    color: 'Crystal White Pearl',
    transmission: 'automatic',
    fuel: 'hybrid',
    doors: 5,
    engine: '2.0 T8 Híbrido Plug-in',
    power: '455 cv',
    features: [
      'Bowers & Wilkins Premium',
      '7 lugares em couro Nappa',
      'Google built-in',
      'Pilot Assist',
      'Teto panorâmico',
      'Air Quality System',
      'Suspensão pneumática',
    ],
    images: [
      'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=1200',
    ],
    description: 'O Volvo XC90 Recharge combina luxo escandinavo com consciência ambiental. Segurança e sustentabilidade em primeiro lugar.',
    status: 'available',
    featured: false,
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
  },
]

export const getVehicleById = (id: string): Vehicle | undefined => {
  return mockVehicles.find(v => v.id === id)
}

export const getFeaturedVehicles = (): Vehicle[] => {
  return mockVehicles.filter(v => v.featured && v.status !== 'sold')
}

export const getAvailableVehicles = (): Vehicle[] => {
  return mockVehicles.filter(v => v.status === 'available')
}

export const mockMessages: ContactMessage[] = [
  {
    id: '1',
    name: 'João Silva',
    email: 'joao.silva@email.com',
    phone: '(11) 99999-1111',
    subject: 'Interesse no Porsche 911',
    message: 'Gostaria de saber mais informações sobre o Porsche 911 Carrera S. Está disponível para test drive?',
    vehicleId: '1',
    createdAt: new Date('2024-01-20'),
    read: false,
  },
  {
    id: '2',
    name: 'Maria Santos',
    email: 'maria.santos@email.com',
    phone: '(11) 98888-2222',
    subject: 'Financiamento Mercedes',
    message: 'Vocês trabalham com financiamento? Tenho interesse no Mercedes-AMG GT 63.',
    vehicleId: '2',
    createdAt: new Date('2024-01-19'),
    read: true,
  },
  {
    id: '3',
    name: 'Carlos Oliveira',
    email: 'carlos.oliveira@email.com',
    phone: '(11) 97777-3333',
    subject: 'Dúvida sobre BMW M4',
    message: 'O BMW M4 Competition aceita troca? Tenho um BMW 330i 2022.',
    vehicleId: '3',
    createdAt: new Date('2024-01-18'),
    read: false,
  },
  {
    id: '4',
    name: 'Ana Pereira',
    email: 'ana.pereira@email.com',
    phone: '(11) 96666-4444',
    subject: 'Visita à loja',
    message: 'Qual o horário de funcionamento? Gostaria de visitar a loja no sábado.',
    createdAt: new Date('2024-01-17'),
    read: true,
  },
]

export const mockSchedulings: Scheduling[] = [
  {
    id: '1',
    vehicleId: '1',
    vehicleName: 'Porsche 911 Carrera S 2024',
    customerName: 'João Silva',
    customerEmail: 'joao.silva@email.com',
    customerPhone: '(11) 99999-1111',
    preferredDate: new Date('2024-01-25'),
    preferredTime: '10:00',
    message: 'Gostaria de fazer um test drive no Porsche 911.',
    status: 'confirmed',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '2',
    vehicleId: '2',
    vehicleName: 'Mercedes-AMG GT 63 2023',
    customerName: 'Maria Santos',
    customerEmail: 'maria.santos@email.com',
    customerPhone: '(11) 98888-2222',
    preferredDate: new Date('2024-01-26'),
    preferredTime: '14:00',
    message: 'Interesse em conhecer o Mercedes pessoalmente.',
    status: 'pending',
    createdAt: new Date('2024-01-19'),
  },
  {
    id: '3',
    vehicleId: '3',
    vehicleName: 'BMW M4 Competition 2024',
    customerName: 'Carlos Oliveira',
    customerEmail: 'carlos.oliveira@email.com',
    customerPhone: '(11) 97777-3333',
    preferredDate: new Date('2024-01-24'),
    preferredTime: '16:00',
    message: 'Quero avaliar o M4 para possível troca.',
    status: 'completed',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '4',
    vehicleId: '6',
    vehicleName: 'Ferrari Roma 2023',
    customerName: 'Pedro Almeida',
    customerEmail: 'pedro.almeida@email.com',
    customerPhone: '(11) 95555-5555',
    preferredDate: new Date('2024-01-27'),
    preferredTime: '11:00',
    message: 'Sonho em dirigir uma Ferrari!',
    status: 'pending',
    createdAt: new Date('2024-01-21'),
  },
]
